name: releases
on:
    push:
        branches:
            - master

jobs:
    changelog:
        runs-on: ubuntu-latest

        steps:
            - uses: google-github-actions/release-please-action@v3
              id: release
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  release-type: node
                  package-name: 'websocket-chat'
